# Generated by Django 5.0 on 2023-12-09 11:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movie_source_uid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.TextField(unique=True)),
                ("page_title", models.TextField(blank=True, null=True)),
                ("score", models.FloatField(blank=True, null=True)),
                ("critic_score", models.FloatField(blank=True, null=True)),
                ("last_crawled", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "data_sources",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("release", models.IntegerField(blank=True, null=True)),
                ("duration", models.SmallIntegerField(blank=True, null=True)),
                (
                    "genres",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=128),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "directors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "actors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("plot", models.TextField(blank=True, null=True)),
                ("image_url", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "movies",
                "managed": False,
            },
        ),
    ]
